### PR TITLE
Fixes hardcoded Apalache path

### LINKED ISSUE #34: Fix hardcoded path to Apalache
Apalache is currently found via a hard-coded path that works in the devcontainer.

Make it more flexible (e.g., check in $PATH).

### PR DESCRIPTION
**Pull request by Kukovec**
closes #34

Instead of looking at a fixed directory, attempts to read the `$APALACHE_HOME` environment variable.

### CODE REVIEW

File: solarkraft/src/environment.d.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+ */
+declare global {
+    namespace NodeJS {
+        interface ProcessEnv {
+            APALACHE_HOME: string
+        }
+    }
+}
+
+export {}
```
Comment (konnov) [inline solarkraft/src/environment.d.ts:13]: why do we need that? Is it some kind of an idiom for the case of running outside of node?

**Review by konnov — APPROVED** [review]
Looks good. I am just a bit puzzled about `environment.d.ts`

File: solarkraft/src/environment.d.ts (hunk 1 above)
Comment (Kukovec) [reply solarkraft/src/environment.d.ts:13]: It's used to specify the `process.env` object's `APALACHE_HOME` field.

Comment (konnov) [reply solarkraft/src/environment.d.ts:13]: Cool. I did not know about that!
